[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.term]
command = "kitty --class kitty-dropterm -e zellij"
animation = "fromTop"
margin = 50
unfocus = "hide"
size = "75% 60%"
max_size = "1920px 100%"
