# users/alice/userInfo.toml
fullName = "Alice Example"
email    = "alice@example.com"
userName = "alice"
shell    = "fish"     # informational; system sets the shell below
editor   = "helix"    # informational for later
roles    = ["workstation"]
