# users/damajha/userInfo.toml
fullName = "Dale Appleby"
email    = "promiscunix@gmail.com"
userName = "damajha"
shell    = "fish"     
editor   = "helix"    
roles    = [ "workstation", "admin"]
sshKeys  = [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOpJBaYruevDAh07TajRf0kDpNA+MkQetaOTq8WAnX1d promiscunix@gmail.com" ]
