# hosts/optiplex/systemInfo.toml
hostName = "optiplex"
ipAddr = "192.168.1.201/24"
networkInterfaceName = "enp2s0"
mainUser = "damajha"

[accounts]
# enroll users whose roles intersect these:
includeRoles = ["workstation"]
# optional per-host tweaks:
extraUsers   = []       # always include (even if no role match)
exclude      = []       # remove, even if role matched
wheelRole    = "admin"  # who gets sudo via role (in addition to mainUser)
