# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/892e6d29-57ce-4d4c-bc2c-3fb23b29477b";
    fsType = "btrfs";
    options = ["subvol=@root" "compress=zstd" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/892e6d29-57ce-4d4c-bc2c-3fb23b29477b";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/892e6d29-57ce-4d4c-bc2c-3fb23b29477b";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd" "noatime"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/892e6d29-57ce-4d4c-bc2c-3fb23b29477b";
    fsType = "btrfs";
    options = ["subvol=@persist" "compress=zstd" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/76E0-1968";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  # HDD with btrfs subvolumes - mount each directly
  # /mnt/critical directory must exist on root filesystem
  fileSystems."/mnt/critical/backups" = {
    device = "/dev/disk/by-uuid/6a443b76-4bc4-4e71-bc47-1aade11d62f6";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime" "subvol=@backups"];
  };

  fileSystems."/mnt/critical/sync" = {
    device = "/dev/disk/by-uuid/6a443b76-4bc4-4e71-bc47-1aade11d62f6";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime" "subvol=@sync"];
  };

  fileSystems."/mnt/critical/services" = {
    device = "/dev/disk/by-uuid/6a443b76-4bc4-4e71-bc47-1aade11d62f6";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime" "subvol=@services"];
  };

  fileSystems."/mnt/critical/temp" = {
    device = "/dev/disk/by-uuid/6a443b76-4bc4-4e71-bc47-1aade11d62f6";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime" "subvol=@temp"];
  };

  # 4TB Storage HDD - main NAS storage
  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/89272f79-0b91-47f9-a791-5fa697eae35c";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
